name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

jobs:

  # -----------------------
  # BACKEND TESTS (PYTHON)
  # -----------------------
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install backend dependencies
      run: pip install -r requirements.txt

    - name: Run backend tests
      run: pytest


  # -----------------------
  # FRONTEND TESTS (VUE)
  # -----------------------
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install frontend dependencies
      run: npm install

    - name: Run frontend tests
      run: npm test
